### ISSUE TITLE
01-aks-create.json file does not exist in the repository

### ISSUE THREAD

**Issue by sawpresto** [Microsoft/SmartHotel360-AKS-DevSpaces-Demo#11]
I'm wanting to recreate the demo but when looking through the docs for the Demo Setup, I'm told to run the 01-aks-create.sh file locally. When looking in the file, it references an ARM template file 01-aks-create.json but I can't find that file in the GitHub repository. Where does this file exist? I've checked both the helm and master branches. I'm not sure if I'm just missing a step in the docs or something else.

Here's the 01-aks-create.sh file located in the setup folder:
```
echo "------------------------------------------------------------"
echo "Creating Cluster ${AKS_NAME} in Resource Group ${AKS_RG}"
echo "------------------------------------------------------------"
az group deployment create -n ${AKS_NAME}create -g ${AKS_RG} --template-file 01-aks-create.json --parameters resourceName=${AKS_NAME} dnsPrefix=${AKS_NAME} servicePrincipalClientId=${SPN_CLIENT_ID} servicePrincipalClientSecret=${SPN_PW} workspaceRegion="Canada Central" enableHttpApplicationRouting=true enableOmsAgent=true
```

**Comment by bradygaster** [comment]
@sawpresto the file is [here](https://github.com/Microsoft/SmartHotel360-AKS-DevSpaces-Demo/blob/helm/provision/01-aks-create.json) in the "provision" folder in this repository. Sorry it was hard to find.

**Comment by sawpresto** [comment]
Great, thank you, @bradygaster!
