### ISSUE TITLE
Clarity required

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/SmartHotel360-AKS-DevSpaces-Demo#9]
[https://github.com/Microsoft/SmartHotel360-AKS-DevSpaces-Demo/blob/helm/docs/03-preload.md#customizing-the-script-for-your-clusters](url)

In the example, there are two clusters mentioned.  Through the demo script we deploy only one cluster. Why is example showing two cluster or how do we get two cluster for what purpose?

**Comment by bradygmsft** [comment]
The setup documentation outlines this in pretty clear detail. We say that is in an array of URLs, then even go on to say that it never hurts to have a backup environment if this is being done as a demo. You only have one cluster, so you'd only need one URI in there. I think the readme is okay as-is. If you feel this is a necessary change, please send us a PR with the change made to the demo script and we'll accept it if it adds value to the reader. Thanks for the issue though!
